[shell]
lang = "ru"
telemetry_enabled = false
offline_mode = false

[shell.panel]
transparency_mode = "soft"
borders = true
shadow = true
launcher_placement = "centered"
control_center_placement = "attached"
wallpaper_placement = "attached"
session_placement = "attached"

[theme]
mode = "dark"
source = "builtin"
builtin = "Gruvbox"

[location]
auto_locate = false
address = "Saint petersburg"

[weather]
enabled = true
unit = "celsius"
effects = true

[wallpaper]
enabled = true
fill_mode = "crop"
directory = "~/Pictures/Wallpapers"
transition = ["fade", "wipe", "disc", "stripes", "zoom", "honeycomb"]
transition_duration = 1500
edge_smoothness = 0.05

[notification]
enable_daemon = true

[osd]
position = "top_right"
background_opacity = 0.97

[bar.main]
position = "top"
thickness = 34
background_opacity = 0.93
radius = 12
margin_h = 4
margin_v = 4
padding = 14
widget_spacing = 6
scale = 1.0
shadow = true
auto_hide = false
reserve_space = true
capsule = true

start = ["launcher", "clock", "sysmon", "active_window", "media"]
center = ["workspaces"]
end = ["tray", "notifications", "volume", "brightness", "network", "keyboard_layout", "battery", "control-center"]

[widget.clock]
format = "{:%H:%M}"
tooltip_format = "{:%A, %B %d, %Y}"

[widget.active_window]
max_length = 145
min_length = 80
display = "icon_and_text"
title_scroll = "hover"

[widget.media]
max_width = 145
panel_show_album_art = true
show_album_art = true
show_artist_first = true
show_progress_ring = true

[widget.keyboard_layout]
display = "short"
show_icon = true
show_label = true
hide_when_single_layout = false

[widget.workspaces]
display = "name"
max_label_chars = 10

[widget.launcher]
use_distro_logo = false
icon = "rocket"

[widget.control-center]
use_distro_logo = false
icon = "noctalia"

[shell.session]
grid = true
grid_columns = 3

[[shell.session.actions]]
action = "lock"
enabled = true
shortcut = "1"

[[shell.session.actions]]
action = "suspend"
enabled = true
shortcut = "2"

[[shell.session.actions]]
action = "hibernate"
enabled = true
shortcut = "3"

[[shell.session.actions]]
action = "reboot"
enabled = true
shortcut = "4"

[[shell.session.actions]]
action = "logout"
enabled = true
shortcut = "5"

[[shell.session.actions]]
action = "shutdown"
enabled = true
shortcut = "6"

[[shell.session.actions]]
action = "reboot_to_uefi"
enabled = true
shortcut = "7"
